### ISSUE TITLE
About preprocess

### ISSUE THREAD

**Issue by LiuMing-Hui** [TencentYoutuResearch/OpenWorld-DeepFakeAttribution#1]
Your work helped me a lot, but while preprocessing the DFFD dataset, I found out that you used a file named "all_img_paths.txt".  And I didn't find it in the dataset. How can I download it? Thank you very much!

**Comment by LiuMing-Hui** [comment]
> Your work helped me a lot, but while preprocessing the DFFD dataset, I found out that you used a file named "all_img_paths.txt". And I didn't find it in the dataset. How can I download it? Thank you very much!

Is it correct for me to replace this file with "train_fake" and "test_fake" provided by DFFD datasrt? Looking forward to your reply.

**Comment by LiuMing-Hui** [comment]
When I run "**Change setting of Semi-Supervised Learning**" in preprocess, I find you use the file "**Protocol2_openset_real_fake_large_merge_meta.csv**" that was not mentioned before. Is it a file that was generated before? Also，I did not find the files "Protocol1_openset_fake_ **val** _merge_meta" and "Protocol2_openset_real_fake_ **val** _merge_meta.csv" used in “train.yaml”. How can I generate them? Thank you very much~

**Comment by ThreeCatsLoveFish** [comment]
Hi Liu, thank you for your interest in our job!

> > Your work helped me a lot, but while preprocessing the DFFD dataset, I found out that you used a file named "all_img_paths.txt". And I didn't find it in the dataset. How can I download it? Thank you very much!
> 
> Is it correct for me to replace this file with "train_fake" and "test_fake" provided by DFFD datasrt? Looking forward to your reply.

That's right, sorry for not clarifying this~


> When I run "**Change setting of Semi-Supervised Learning**" in preprocess, I find you use the file "**Protocol2_openset_real_fake_large_merge_meta.csv**" that was not mentioned before. Is it a file that was generated before?

Good question, thanks for pointing out this issue. The file `openset_real_fake_large_merge_meta.csv` is just the same file as `Protocol2_openset_real_fake_large_merge_meta.csv`, and we renamed this make sure that the name of our config file matches our protocol setting in the paper. You can simply run the command:
```bash
cp openset_real_fake_large_merge_meta.csv Protocol2_openset_real_fake_large_merge_meta.csv
```

> Also, I did not find the files "Protocol1_openset_fake_ **val** _merge_meta" and "Protocol2_openset_real_fake_ **val** _merge_meta.csv" used in “train.yaml”. How can I generate them? 

**val** refers to a standard-size version of the benchmark, which can be obtained by only using 1/5 data of the **large** version file. By using **val**, you can check whether your method is effective more rapidly, with less training and test data. You can obtain this by randomly selecting 1/5 data for each method.

**Comment by LiuMing-Hui** [comment]
> 嗨，刘，感谢您对我们工作的关注！
> 
> > > 你的工作对我帮助很大，但是在预处理DFFD数据集时，我发现你使用了一个名为“all_img_paths.txt”的文件。而且我在数据集中没有找到它。如何下载？谢谢！
> > 
> > 
> > 用DFFD datasrt提供的“train_fake”和“test_fake”替换此文件是否正确？期待您的回复。
> 
> 没错，对不起没有澄清这个~
> 
> > 当我在预处理中运行“**更改半监督学习的设置**”时，我发现您使用了之前未提及的文件“**Protocol2_openset_real_fake_large_merge_meta.csv**”。是之前生成的文件吗？
> 
> 好问题，感谢您指出这个问题。该文件与 的文件相同，我们重命名了它，以确保我们的配置文件的名称与我们在论文中的协议设置相匹配。您可以简单地运行以下命令：`openset_real_fake_large_merge_meta.csv``Protocol2_openset_real_fake_large_merge_meta.csv`
> 
> ```shell
> cp openset_real_fake_large_merge_meta.csv Protocol2_openset_real_fake_large_merge_meta.csv
> ```
> 
> > 另外，我没有找到“train.yaml”中使用的文件“Protocol1_openset_fake_ **val** _merge_meta”和“Protocol2_openset_real_fake_ **val** _merge_meta.csv”。如何生成它们？
> 
> **val** 是指基准测试的标准大小版本，仅使用**大**版本文件的 1/5 数据即可获得。通过使用 **val**，您可以更快地检查您的方法是否有效，同时使用更少的训练和测试数据。您可以通过为每种方法随机选择 1/5 个数据来获得此信息。

Thank you very much for your reply!
