### ISSUE TITLE
About the Table 1. in you paper and the DFA dataset

### ISSUE THREAD

**Issue by LiuMing-Hui** [TencentYoutuResearch/OpenWorld-DeepFakeAttribution#2]
Thank you very much for your outstanding work and I would like to follow your work to continue my research. 
In Table 1. in your paper, is the number **"1500" "500" in "labeled" and "unlabeled"** columnsn is the number of the samples? After running your code **"create_academic_meta.ipynb**" ,  the number of the samples is **not consistent** with the the number in the table.
If I want to get the performance in Table 2, **how much** data needs to be trained on? Should the total amount of training data be consistent with your Table 1 or your code?

**Comment by ThreeCatsLoveFish** [comment]
> If I want to get the performance in Table 2, **how much** data needs to be trained on? Should the total amount of training data be consistent with your Table 1 or your code?

Exactly, the number of samples should be the same as the one shown in Table 1, and you can obtain the training data from Table 1 refers to **val** in #1 .
